### ISSUE TITLE
Exporting takes long time

### ISSUE THREAD

**Issue by gtusar** [Suplanus/EplanElectricP8Automatisieren#1]
Hi,
first of all thank you for sharing such a good repository for Eplan scripts.

I am facing a problem with exporting BOM into a XML file. When I use the script like in your "14_Beispiele -07_Partlist", the operation is taking unusually long. Sometimes even more than five minutes. 

The thing is, that if I export the BOM with right-mouse-click on the Bill of material, file is created in just a few seconds. 

Have you maybe encountered such behaviour before?
Is there another way to export a BOM?

Thank you.

Best regards, Gregor

**Comment by Suplanus** [comment]
Where you can make a right click to export?

The long export i think is caused by EPLAN...

**Comment by gtusar** [comment]
I can right click on a Bill of materials window.
Project data -> Parts/Devices -> Bill of materilas navigator.

I found out that the root cause for long export time is, that Eplan inserts every single detail into BOM, also the parts of 3D models.

I am now searching for a documentation for the SQLFILTERPART in your script. And in the meanwhile I really hope that this will solve my problem. :)

Do you have any information about that?

Thank you for your response!

**Comment by Suplanus** [comment]
This export is running 30s in the eplan demo project... 
There is no possibility with scripting to do this with an other way :/

**Comment by gtusar** [comment]
30 seconds is still OK, I had to wait about 10 minutes to get the export file. 

So you don't have any information about the SQLFILTERPART?

Since in the [help page](http://eplan.help/help/platform/2.6/en-US/help/Content/htm/availableactions_o_partslist.htm) it says that default is "1=1", I assumed that I have to insert conditions after WHERE clause of a normal SQL command.
But so far I could't get it working, while the debugging is almost impossible in this case.

**Comment by Suplanus** [comment]
No, have no information or tests with this parameter...
I would ask the EPLAN support why your script is taking so long... they have possiblities to debug :)

**Comment by gtusar** [comment]
Ok, thank you anyways.

And BTW, thanks for cool examples!
